version: "3.8"
services:
  postgres:
    image: postgres:13
    restart: always
    env_file: postgres.prod.env
    volumes:
      - "./data/postgres/pgdata/:/var/lib/postgresql/data/"
    networks:
      - postgres
  backend:
    image: registry.gitlab.com/safeblues/backend/backend
    restart: always
    env_file: backend.prod.env
    ports:
      - 5432:5432
    depends_on:
      - postgres
    networks:
      - postgres
      - nginx
  envoy:
    image: registry.gitlab.com/safeblues/backend/proxy
    restart: always
    networks:
      - nginx
  nginx:
    image: registry.gitlab.com/safeblues/backend/nginx
    restart: always
    env_file: nginx.prod.env
    volumes:
      - "./data/certs/:/certs/"
      - "./data/nginx/logs/:/var/log/nginx/"
    ports:
      - 443:443
      - 8443:8443
    networks:
      - nginx
networks:
  postgres:
    driver: bridge
  nginx:
    driver: bridge
