version: "3.8"
services:
  postgres:
    image: postgres:13
    restart: always
    env_file: postgres.prod.env
    volumes:
      - "./data/postgres/pgdata/:/var/lib/postgresql/data/"
    ports:
      - 5432:5432
  backend:
    image: registry.gitlab.com/safeblues/backend/backend
    restart: always
    env_file: backend.prod.env
    depends_on:
      - postgres
  envoy:
    image: registry.gitlab.com/safeblues/backend/proxy
    restart: always
    expose:
      - 8888
      - 9901
  nginx:
    image: registry.gitlab.com/safeblues/backend/nginx
    restart: always
    env_file: nginx.prod.env
    volumes:
      - "./data/certs/:/certs/"
      - "./data/nginx/logs/:/var/log/nginx/"
    ports:
      - 443:443
      - 9443:9443
