version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-sb"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1d70lzd1aq5ma"
s3_prefix = "hello-sb"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
