# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sb.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sb.proto',
  package='sb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08sb.proto\x12\x02sb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf5\x01\n\x06Strand\x12\x11\n\tstrand_id\x18\x01 \x01(\x03\x12.\n\nstart_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1b\n\x13seeding_probability\x18\x04 \x01(\x01\x12\x1d\n\x15infection_probability\x18\x05 \x01(\x01\x12\x1e\n\x16incubation_period_days\x18\x06 \x01(\x01\x12\x1e\n\x16infectious_period_days\x18\x07 \x01(\x01\"\x8b\x01\n\x0fInfectionReport\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\"\n\x1a\x63urrent_incubating_strands\x18\x02 \x03(\x03\x12 \n\x18\x63urrent_infected_strands\x18\x03 \x03(\x03\x12\x1f\n\x17\x63urrent_removed_strands\x18\x04 \x03(\x03\"+\n\x0cStrandUpdate\x12\x1b\n\x07strands\x18\x01 \x03(\x0b\x32\n.sb.Strandb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_STRAND = _descriptor.Descriptor(
  name='Strand',
  full_name='sb.Strand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='strand_id', full_name='sb.Strand.strand_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='sb.Strand.start_time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='sb.Strand.end_time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seeding_probability', full_name='sb.Strand.seeding_probability', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='infection_probability', full_name='sb.Strand.infection_probability', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='incubation_period_days', full_name='sb.Strand.incubation_period_days', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='infectious_period_days', full_name='sb.Strand.infectious_period_days', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=295,
)


_INFECTIONREPORT = _descriptor.Descriptor(
  name='InfectionReport',
  full_name='sb.InfectionReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='sb.InfectionReport.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_incubating_strands', full_name='sb.InfectionReport.current_incubating_strands', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_infected_strands', full_name='sb.InfectionReport.current_infected_strands', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_removed_strands', full_name='sb.InfectionReport.current_removed_strands', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=437,
)


_STRANDUPDATE = _descriptor.Descriptor(
  name='StrandUpdate',
  full_name='sb.StrandUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='strands', full_name='sb.StrandUpdate.strands', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=482,
)

_STRAND.fields_by_name['start_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_STRAND.fields_by_name['end_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_STRANDUPDATE.fields_by_name['strands'].message_type = _STRAND
DESCRIPTOR.message_types_by_name['Strand'] = _STRAND
DESCRIPTOR.message_types_by_name['InfectionReport'] = _INFECTIONREPORT
DESCRIPTOR.message_types_by_name['StrandUpdate'] = _STRANDUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Strand = _reflection.GeneratedProtocolMessageType('Strand', (_message.Message,), {
  'DESCRIPTOR' : _STRAND,
  '__module__' : 'sb_pb2'
  # @@protoc_insertion_point(class_scope:sb.Strand)
  })
_sym_db.RegisterMessage(Strand)

InfectionReport = _reflection.GeneratedProtocolMessageType('InfectionReport', (_message.Message,), {
  'DESCRIPTOR' : _INFECTIONREPORT,
  '__module__' : 'sb_pb2'
  # @@protoc_insertion_point(class_scope:sb.InfectionReport)
  })
_sym_db.RegisterMessage(InfectionReport)

StrandUpdate = _reflection.GeneratedProtocolMessageType('StrandUpdate', (_message.Message,), {
  'DESCRIPTOR' : _STRANDUPDATE,
  '__module__' : 'sb_pb2'
  # @@protoc_insertion_point(class_scope:sb.StrandUpdate)
  })
_sym_db.RegisterMessage(StrandUpdate)


# @@protoc_insertion_point(module_scope)
